version: '3.7'
services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    networks:
      - limit_counter
    volumes:
      - ./:/code
    command: bash
  aerospike:
    container_name: aerospike
    image: aerospike:4.6.0.4
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    networks:
      - limit_counter
networks:
  limit_counter:
    name: limit_counter
    driver: bridge
